name = "algonest-auth"
main = "worker.js"
compatibility_date = "2026-07-04"

[vars]
EXTENSION_ID = "bbccdkeopnkkfleidompgfkecaenpkhf"
GITHUB_REDIRECT_URI = "https://bbccdkeopnkkfleidompgfkecaenpkhf.chromiumapp.org/"

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 10, period = 60 }