import type { StatsData } from "./stats";

export function generateREADME(stats: StatsData, repoName: string): string {
  const totalSolved = stats.total_solved;
  const currentStreak = stats.current_streak;
  const easyCount = stats.by_difficulty.Easy ?? 0;
  const mediumCount = stats.by_difficulty.Medium ?? 0;
  const hardCount = stats.by_difficulty.Hard ?? 0;

  let readmeContent = `---
# 🧩 ${repoName} — LeetCode Solutions

![Total](https://img.shields.io/badge/Solved-${totalSolved}-blueviolet?style=flat-square)
![Streak](https://img.shields.io/badge/Streak-${currentStreak}%20days-orange?style=flat-square)
![Easy](https://img.shields.io/badge/Easy-${easyCount}-00b8a3?style=flat-square)
![Medium](https://img.shields.io/badge/Medium-${mediumCount}-ffa116?style=flat-square)
![Hard](https://img.shields.io/badge/Hard-${hardCount}-ff375f?style=flat-square)

---
`;

  readmeContent += `
## 📊 Progress by Topic

| Topic | Solved | Progress |
|-------|--------|----------|
`;

  const topicEntries = Object.entries(stats.by_topic);
  const maxTopicCount = topicEntries.reduce((max, [, count]) => Math.max(max, count), 0);

  if (topicEntries.filter(([, count]) => count > 0).length === 0) {
    readmeContent += `| — | — | — |
`;
  } else {
    for (const [topic, count] of topicEntries.filter(([, count]) => count > 0).sort((a,b) => b[1] - a[1])) {
      const filled = Math.round((count / maxTopicCount) * 20);
      const bar = "█".repeat(filled) + "░".repeat(20 - filled);
      readmeContent += `| ${topic} | ${count} | ${bar} |
`;
    }
  }

  readmeContent += `
## 🎯 Difficulty Breakdown

| Difficulty | Count |
|------------|-------|
| ![Easy](https://img.shields.io/badge/Easy-00b8a3?style=flat-square) | ${easyCount} |
| ![Medium](https://img.shields.io/badge/Medium-ffa116?style=flat-square) | ${mediumCount} |
| ![Hard](https://img.shields.io/badge/Hard-ff375f?style=flat-square) | ${hardCount} |
`;

  readmeContent += `
## 🕐 Recently Solved

| # | Problem | Topic | Difficulty | Language | Date |
|---|---------|-------|------------|----------|------|
`;

  const recentSolves = stats.solve_log.slice(0, 10); 
  if (recentSolves.length === 0) {
    readmeContent += `| — | — | — | — | — | — |
`;
  } else {
    for (let i = 0; i < recentSolves.length; i++) {
      const solve = recentSolves[i];
      let badgeUrl = "";
      if (solve.difficulty === "Easy") {
        badgeUrl = "https://img.shields.io/badge/Easy-00b8a3?style=flat-square";
      } else if (solve.difficulty === "Medium") {
        badgeUrl = "https://img.shields.io/badge/Medium-ffa116?style=flat-square";
      } else if (solve.difficulty === "Hard") {
        badgeUrl = "https://img.shields.io/badge/Hard-ff375f?style=flat-square";
      }
      const problemLink = `./solutions/${solve.topic}/${solve.slug}.md`;
      readmeContent += `| ${i + 1} | [${solve.title}](${problemLink}) | ${solve.topic} | ![${solve.difficulty}](${badgeUrl}) | ${solve.language} | ${solve.date} |\n`;
    }
  }

  readmeContent += `
## 🗂️ By Language

| Language | Count |
|----------|-------|
`;
  const languageEntries = Object.entries(stats.by_language);
  if (languageEntries.length === 0) {
    readmeContent += `| — | — |
`;
  } else {
    for (const [lang, count] of languageEntries.filter(([, count]) => count > 0).sort((a,b) => b[1] - a[1])) {
      readmeContent += `| ${lang} | ${count} |
`;
    }
  }

  const now = new Date();
  const utcDate = now.toISOString().split("T")[0];
  const utcTime = now.toISOString().split("T")[1].substring(0, 5);

  readmeContent += `
---
*Auto-generated by [AlgoNest](https://github.com/your-repo/algonest) 
— last updated ${utcDate} ${utcTime} UTC*
---
`;

  return readmeContent;
}
